channels:
- conda-forge
dependencies:
- python=3.7.11
- pip
- pip:
  - mlflow
  - cffi==1.15.0
  - defusedxml==0.7.1
  - dill==0.3.4
  - googleapis-common-protos==1.55.0
  - keras==2.8.0
  - pandas==1.3.5
  - pillow==9.0.1
  - scipy==1.7.3
  - tensorflow==2.8.0
  - tensorflow-datasets
name: mlflow-env
